### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by TKlerx** [EdwardRaff/JSAT#10]
Very nice, that you set up a maven repository. Maybe, for those who are not familiar with maven, you could upload the jar to the releases tab.
Could you also add src and doc jars to your maven repo? (with maven-source-plugin and maven-javadoc-plugin).
What about adding JSAT to the central maven repository?! Then anyone could find JSAT without changing the pom file

**Comment by EdwardRaff** [comment]
>Very nice, that you setup a maven repository. Maybe, for those who are not familiar with maven, you could upload the jar to the releases tab.

Fair enough, I'll add it. 

>Could you also add src and doc jars to your maven repo? (with maven-source-plugin and maven-javadoc-plugin).

aww, darn. I thought I set it up to do that. 

>What about adding JSAT to the central maven repository?! Then anyone could find JSAT without changing the pom file

I really don't know what's involved in doing that. And right now there are enough things that I still want to fix that I'm not sure I want to add it to maven central. Once it's more "polished" perhaps. I mean, people still have to edit their pom to add the dependency - right?

**Comment by TKlerx** [comment]
>aww, darn. I thought I set it up to do that. 

add this:
```
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.4</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<phase>deploy</phase>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.4</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<phase>deploy</phase>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
>I really don't know what's involved in doing that. And right now there are enough things that I still want to fix that I'm not sure I want to add it to maven central. Once it's more "polished" perhaps. I mean, people still have to edit their pom to add the dependency - right? 

Yes, people still have to edit their pom. But adding a dependency is supported by (most) GUIs whereas adding a custom repo is not.
But yeah, it is not urgent ;)

**Comment by herrbpl** [comment]
Looks like http://www.edwardraff.com/maven-repo/com/edwardraff/JSAT/0.0.2/JSAT-0.0.2.pom is unreachable. Better perhaps use central repo?

**Comment by RaffEdwardBAH** [comment]
@herrbpl I can reach it, try again?. I can look into what adding to central takes, its just not been a priority for me.

**Comment by EdwardRaff** [comment]
@herrbpl I can reach it, try again?. I can look into what adding to central takes, its just not been a priority for me.

**Comment by herrbpl** [comment]
Strange, it works now.. Before it was unreachable (whole host, not only url)..

**Comment by TKlerx** [comment]
I had the same problem (unreachable).
Maybe some temporary DNS problem.
I think adding it to maven central is not that complicated, but you have to somehow sign up and have your request checked.
If you need some requests, I would request adding JSAT to maven central.

**Comment by EdwardRaff** [comment]
JSAT should now be in Central Repo https://search.maven.org/#artifactdetails%7Ccom.edwardraff%7CJSAT%7C0.0.2%7Cjar
