### ISSUE TITLE
Save and Load Classifier

### ISSUE THREAD

**Issue by HWBK** [EdwardRaff/JSAT#12]
Hi,

Is there any way save to a classifer once trained so it can be reloaded later?
I tried serializing/deserializing a DANN classifier using ObjectOutputStream/ObjectInputStream but VPNode was not serializeable on read.
Adding Serializeable to VPNode gave "no valid constructor" on read.
Adding a no-argument constructor to VPNode gave the same error.

NaiveBayes classifier can be serialized/deserialized.

Thanks,

**Comment by EdwardRaff** [comment]
Serialization is the only way right now. I have forgotten to leave no-argument constructors on many classes. Adding a no-arg should have fixed it, so I will look into it. 

You may find serialization frameworks like Kyro useful, it will probably be faster than the standard java serialization.

**Comment by chhh** [comment]
@HWBK Try serializing with this library (FST) https://github.com/RuedigerMoeller/fast-serialization, it is quite a bit more tolerant, than default java serialization.

**Comment by EdwardRaff** [comment]
Fixed in b8c0b378fbc4486be4f3822d329a736a6b05bc16 , build from head and it should be fine.

**Comment by HWBK** [comment]
Using FST on the previous build gave unserializeable for jsat.linear.vectorcollection.VPTree$VPLeaf.
The latest build works fine even with ObjectOutputStream/ObjectInputStream.
Thank you.
