### ISSUE TITLE
Eclipse/Netbeans Refactoring (including upgrading to java 8)

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#14]
I ran Eclipse's and Netbeans' upgrade assistant / refactor suggestions on the code base, and it is quite extensive.  In many places, too pushy and/or breaks the code.

Some are great suggestions!  Lots of safer braces, using Strings in switch statements, removing unnecessary else blocks after a return, Java 7 diamonds in the constructors, ditching unnecessary casts, etc etc.  IMHO totally worth it.

Some are wrong suggestions, like how to handle templates with DataSet.  In general, all of the raw type suggestions take a moment to look at.  You may have a better solve.

Some of the Java 8 suggestions are iffy, like converting the for loops to streams, and I don't know if that would be a bad idea, or a really interesting idea because then they could be run in parallel.  You *may* be able to slim down the existing parallel code using parallel streams and lambdas.

**Comment by EdwardRaff** [comment]
I have a lot of plans for upgrading JSAT to Java 8! That upgrade is also going to be an opportunity for some refactoring, as I am planning on using the Default methods in interfaces to simplify a lot of the code for most classes. 

My plan is to keep JSAT one major version behind the current Java. So I'll refactor to Java 8 once Java 9 gets released. I was going to move JSAT to Java 7 a while ago, but there wasn't much feature wise to take advantage of that would offset the number of people still using Java 6 at the time, so I'm skipping that one. 

> like converting the for loops to streams, and I don't know if that would be a bad idea, or a really interesting idea because then they could be run in parallel. 

That is a very iffy one. For simple stuff for loops are just as clear, and Java 8 lambdas obscure some optimizations that would normally take place. 

>You may be able to slim down the existing parallel code using parallel streams and lambdas.

There is a *lot* of opportunity for that. One of my big concerns is that JSAT allows of implicitly limiting parallelism by passing an executor that can only spawn so many threads. However lambdas don't allow  for specifying the maximum number of threads in a parallel stream, making the features incompatible. 

So currently I'm considering removing the use of thread pools to indicate a desire to train in parallel, and instead making it a method with some indicator (something like "trainP") - but it will then always to try to use all available cores. So far I haven't had much use cases for needing to control the amount of threads used during training, so I'm wondering if anyone else uses that implicit feature or if it will be safe for me to remove.

**Comment by salamanders** [comment]
This person's opinion: Some Classifiers support a ParallelTrainable interface which has a isParallel(t/f) switch (defaults to true) so everyone who calls the usual universal train() method gets all the parallel goodness without ever having to worry.   But they could still turn it off / make it single threaded if they need to by setting it to false.
