### ISSUE TITLE
Example of how to build a DataSet from scratch

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#19]
Getting data in is always painful - JSAT much less than most.
I've been going through the test classes and Loaders, and was looking for the most straightforward "load this data into a classifier" example.

I've got the data available as a [Table of Strings](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Table.html) and would need to figure out which cols were "doubles in disguise" vs. classes - but it feels like I'm reinventing wheels past that point.  All the code of "take this list of strings, convert them to int indexed lookup tables, use that to create a data point, add those data points to a list, finally put the list into a Simple(?)DataSet" - can I do it in a generic way?

**Comment by EdwardRaff** [comment]
Unfortunately I'm very busy with some work right now, so getting to all these is going to take a bit. 

I'm not sure what you are storing in your Table, you will have to determine if your features should be numeric or categorical yourself. Does the below code snippet help? 


```java
    public static void main(String[] args)
    {
        //Some random data we want to convert to a DataSet object manually 
        Random rand = new XORWOW();
        double[][] someStuffIWantToMakeIntoADataSet = new double[20][6];
        for(int i = 0; i < someStuffIWantToMakeIntoADataSet.length; i++)
            for(int j = 0; j < someStuffIWantToMakeIntoADataSet[i].length; j++)
                someStuffIWantToMakeIntoADataSet[i][j] = rand.nextDouble();
        
        //Lets decide the first 2 features are categorical and the rest are just numeric
        
        //First we need the list the categories. Well create 1 categorie with 2 options and a 2nd category with 3 options. 
        CategoricalData[] categories = new CategoricalData[]
        {
            new CategoricalData(2), new CategoricalData(3)
        };
        
        SimpleDataSet sds = new SimpleDataSet(categories, 4);
        
        for(double[] row : someStuffIWantToMakeIntoADataSet)
        {
            //first a place to store the categorical values. 
            int[] catValues = new int[categories.length];
            catValues[0] =  (int) Math.round(row[0]);//first cat will be whether the value was closer to 0 or 1
            catValues[1] =  (int) Math.round(row[1]*2);//similar for second
            //Next we need a place to store the numeric features
            Vec numericValues = new DenseVector(4);
            for(int i = 0; i < 4; i++)
                numericValues.set(i, row[2+i]);
            DataPoint dp = new DataPoint(numericValues, catValues, categories);
            //now just add to the dataset
            sds.add(dp);
        }

        //done, we have made a data set
    }
```

**Comment by salamanders** [comment]
Perfect!  Exactly what I was looking for - things like adding to the Vec one at a time being ok, not caring what the strings were that correspond to a category integer and just saving the final number - great stuff.
