### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DiegoCatalano** [EdwardRaff/JSAT#24]
Hello Edward,

Your library is incredible, I'm developing too a [framework](https://github.com/DiegoCatalano/Catalano-Framework) for ML, Image processing and others areas in Computer Science.

My project has born from the [AForge.NET](http://www.aforgenet.com/) and [Accord.NET](http://accord-framework.net/) and has the same license LGPL. I would like to know, if you can change the license GPL for to LGPL or at least some portions.

Cheers !

**Comment by EdwardRaff** [comment]
I will not be changing the license of JSAT, it will remain publicly available under the GPL. Those who want to negotiate for an alternative license are free to contact me to do so. Otherwise, the sharing requirements of the GPL are my "compensation" for the code I've written and made available.
