### ISSUE TITLE
Build problem in Eclipse environment

### ISSUE THREAD

**Issue by NikolaMorena** [EdwardRaff/JSAT#26]
Thank you for sharing the great job you have done with the community.

While build works with Maven, I had a trouble compiling the code from Eclipse (Luna, Java 1.8).  For  methods loadSimple, loadClassification and loadRegression of class JSATData, compilation failed in the casts of load method response, e.g:
return (SimpleDataSet) load(inRaw, true));
Compile error is: Cannot cast from DataSet<DataSet<DataSet<Type>>> to SimpleDataSet

Guess it's specific to my dev environment, so I'm not sending a pull request but just sharing a workaround with "double casting":

return (SimpleDataSet) ((DataSet<?>)load(inRaw, true));

**Comment by EdwardRaff** [comment]
Can you try this with Netbeans/ just the command line. I want to know if this is a Java 1.8 issue, or if this is an issue with the Eclipse compiler.

**Comment by NikolaMorena** [comment]
It's not a Java 1.8 issue. I've tried both with Java 1.6 and Java 1.7 with
the same results.

**Comment by EdwardRaff** [comment]
Sorry, I'm not sure if I'm communicating well. My question is if Java 1.8 causes the issue or not. Eclipse has its own separate compiler, ecj, that it likes to use instead of javac. If Java 1.8 changed slightly and the old code is no longer valid, I will change it. If Only ecj causes the issue, then we should file a bug report with them.

**Comment by NikolaMorena** [comment]
I'm pretty sure that Java 1.8 is not the problem. My default Eclipse
compliance settings was 1.7 and Java build path was set to 1.7 library
initially and build failed. I changed this to 1.8 hoping that may help,
without success. On the other hand, maven builds project fine with Java
1.8 in my console environment.

**Comment by EdwardRaff** [comment]
If that's the case, I'm not sure what I can do. I've built JSAT in Eclipse with 1.7 before. I can try it again later, but unless that reveals something I don't think I can help.

**Comment by EdwardRaff** [comment]
Using latest version of Eclipse, it is giving me errors too. But only in Eclipse. Very weird.

**Comment by NikolaMorena** [comment]
Does my workaround with double casting work for you?
Does it break anything?

**Comment by EdwardRaff** [comment]
I changed the load methods type to just use the wild card directly, it makes more sense and avoids the Eclipse issue. If you could pull and confirm I'll close the issue

**Comment by NikolaMorena** [comment]
Yes Edward, it works now, thanks.

**Comment by EdwardRaff** [comment]
Awesome, thanks!
