### ISSUE TITLE
Normal Distribution returns values >1 and NaN

### ISSUE THREAD

**Issue by TKlerx** [EdwardRaff/JSAT#28]
Hi,

I just found a strange behavior:
The following Unit test methods fail:

```
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import jsat.distributions.Normal;
public class TestNormal {
	static Normal n = new Normal(811.4250871080139d, 1540.8594859716793d);

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
		n = new Normal(811.4250871080139d, 1540.8594859716793d);
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void test1() {
		assertTrue(n.cdf(44430.0d) <= 1);
	}

	@Test
	public void test2() {
		assertFalse(Double.isNaN(n.cdf(67043.0)));
	}
}
```

Can you reproduce this? Is it expected? Did I miss something?

**Comment by EdwardRaff** [comment]
I can reproduce, you've given two values that are over 28 stnd deviations away from the mean! It just a numerical computation error, I'll add a check that returns 1.0 for the CDF for excessively large values like that. 

For the 44430 case, the true CDF should be about 0.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999187613053034057340640164297. So I think rounding up to 1 exactly will be fine :)

**Comment by EdwardRaff** [comment]
Should be fixed, please confirm!

**Comment by TKlerx** [comment]
Works for me ;)
Amazing how fast you responded and fixed it.
Thanks alot!
