### ISSUE TITLE
Tree-based regressors give null pointer exception on .regress

### ISSUE THREAD

**Issue by graemedouglas** [EdwardRaff/JSAT#33]
The following example gives me a null-pointer exception for version 0.0.3 of the library. Seems to be that the `root` value in the tree learners is null? Did I do something wrong?

    package demo;
    
    import java.util.List;
    import java.util.LinkedList;
    
    import jsat.classifiers.DataPoint;
    import jsat.linear.DenseVector;
    import jsat.linear.Vec;
    import jsat.regression.RegressionDataSet;
    import jsat.classifiers.trees.RandomForest;
    import jsat.classifiers.trees.DecisionTree;
    import jsat.regression.MultipleLinearRegression;
    import jsat.regression.Regressor;
    
    public class TreeRegressionDemo
    {
    	public static void main(String[] args)
    	{
    		double[][]			data	= new double[][]{{1.0, 1.5}, {2.0, 2.5}, {3.0, 3.5}};
    		double[]			y		= new double[]{2.0, 4.0, 3.0};
    		List<DataPoint>		points	= new LinkedList<DataPoint>();

    		for (int irow = 0; irow < data.length; irow++)
    		{
    			Vec				vec		= new DenseVector(data[irow].length+1);
    			
    			for (int icol = 0; icol < data[irow].length; icol++)
    			{
    				vec.set(icol, data[irow][icol]);
    			}
    			vec.set(data[irow].length, y[data[irow].length-1]);
    			
    			DataPoint		point	= new DataPoint(vec);
    			points.add(point);
    		}
		
		RegressionDataSet	dataSet	= new RegressionDataSet(points, data[0].length);
		
		RandomForest		forest	= new RandomForest(10);
		DecisionTree		tree	= new DecisionTree();
		MultipleLinearRegression
							mlr		= new MultipleLinearRegression();
		forest.autoFeatureSample();
		Regressor			regressor
									= forest;
		
		regressor.train(dataSet);
		
		DataPoint			testPoint
									= dataSet.getDataPoint(0);
		System.out.println(testPoint);
		double 				result	= regressor.regress(testPoint);
		System.out.println(result);
	}
    }

**Comment by EdwardRaff** [comment]
Whats the purpose of this line 

>vec.set(data[irow].length, y[data[irow].length-1]); 

While odd, that shouldn't break anything. I will investigate this weekend.

**Comment by graemedouglas** [comment]
Uhh, I might have done something quite stupid. I thought I needed to add my response variable to the vector? I flag it as such later with

    RegressionDataSet   dataSet = new RegressionDataSet(points, data[0].length);

When I tested with basic MultipleLinearRegression, I got the result I expected. Maybe that explains it? I genuinely hope it is my mistake though. And thanks for taking a look!

**Comment by EdwardRaff** [comment]
So, what was happening is that there is a minimum number of samples required for a decision tree to consider a split (and a minimum number of nodes to occur in each leaf for the split to be considered). The default is 10, which is more than you data - so it silently failed to construct the node causing your null pointer. I've changed the default behavior to build a single stump when this happens, which may not be the best - but will avoid this very undesirable behavior. 

You can change the min samples with the `setMinSamples` method, but probably best to test on something a bit larger. Sorry about that! 

If you can grab the master branch and confirm it works for you too, I'll close this issue.

**Comment by EdwardRaff** [comment]
Oh, and if you know you want regression - you should construct your dataset like this. 

```java
for (int irow = 0; irow < data.length; irow++)
{
        Vec vec = new DenseVector(data[irow].length);

        for (int icol = 0; icol < data[irow].length; icol++)
        {
                vec.set(icol, data[irow][icol]);
        }
            

        DataPoint point = new DataPoint(vec);
        dataSet.addDataPoint(point, y[data[irow].length-1]);
}
```

This is more clear about what you want, and avoids a needless memory copy.

**Comment by graemedouglas** [comment]
Hi Edward,

Thanks! I even thought about adding more data and I managed to not.

Anyhow, that worked. :) Thank you for your time!

**Comment by EdwardRaff** [comment]
No problem, hope JSAT will be helpful now! Sorry it took me so long, busy weekend.
