### ISSUE TITLE
PCA class

### ISSUE THREAD

**Issue by javicid** [EdwardRaff/JSAT#38]
Not completely sure about this, but shouldn't the "return" statement at line 120 of jsat.datatransform.PCA be a "break" statement? Otherwise P may never get initialized.

Also, the "scores" list declared at line 85 is never used.

**Comment by EdwardRaff** [comment]
I think you are right, I'll try and take a closer look at it this weekend.

**Comment by EdwardRaff** [comment]
Turns out I forgot a larger convergence loop ANd that line was wrong! Fixed now. I'll try and find the original source I was reading before I remove the scores object. I think it was left for added stuff to implement later.
