### ISSUE TITLE
Serialization exception for CategoricalResults

### ISSUE THREAD

**Issue by zpeczoli** [EdwardRaff/JSAT#39]
Serialization of a trained RandomForest classifier results in Exception 
`Class jsat.classifiers.CategoricalResults does not implement Serializable or externalizable`

**Comment by EdwardRaff** [comment]
Thanks for the bug catch! Should be fixed. Confirm and I'll close.

**Comment by zpeczoli** [comment]
Looks ok, thanks for the fix - and for the great library!

Small remark: in JSAT/test/jsat/TestTools.java you replaced the word "copy" in the GPL text with deepCopy :-)

**Comment by EdwardRaff** [comment]
Ughhh, damn you refactoring support! Thanks for that catch too! 

Hope JSAT is more helpful with the fix!
