### ISSUE TITLE
missing class - jsat.graphing.CategoryPlot;

### ISSUE THREAD

**Issue by mulloymorrow** [EdwardRaff/JSAT#40]
Checking out your project. Looks promising!  
Going through your [wiki](https://github.com/EdwardRaff/JSAT/wiki/Applying-Data-Transformations-and-Visualizing), I noticed you mention the class: `CategoryPlot`.
However, there doesn't seem to be such a class in your repo.

**Comment by EdwardRaff** [comment]
It was removed some time ago, I gota remove that. 

I'm currently working on an update to the examples & improvements in unit test reliability, so thanks for pointing out! I'll close this once I make the update

**Comment by EdwardRaff** [comment]
Finally updated those two examples! Sorry for the delay, I've been dealing with some health issues.
