### ISSUE TITLE
SystemInfo.L2CacheSize throws errors on Google App Engine

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#42]
Even though it identifies as  a Linux OS, you can't call binaries.   I'm guessing the same might be true (sometimes) for containers.  IMHO better to lower the log severity so as not to clutter logs.

https://github.com/EdwardRaff/JSAT/blob/master/JSAT/src/jsat/utils/SystemInfo.java

**Comment by EdwardRaff** [comment]
Hadn't thought of that scenario. I'll adjust the severity when I get home.

**Comment by EdwardRaff** [comment]
Is there a environment variable to detect if I'm running in a google app engine? If so I could check that and avoid throwing an error at all.

**Comment by salamanders** [comment]
Best I found was System.getProperty("com.google.appengine.runtime.version")
http://stackoverflow.com/questions/4140747/identify-whether-is-code-running-on-app-engine-runtime-java
