### ISSUE TITLE
FR: Regression w/ bartMachine

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#44]
[This person over here](https://mlr-org.github.io/Benchmarking-mlr-learners-on-OpenML/) had a comparison of various algos and said [bartMachine](https://arxiv.org/pdf/1312.2171.pdf) was the winning Regression algorithm by a large margin.

Request that it be added to JSAT.

**Comment by EdwardRaff** [comment]
This looks rather complicated to implement. I'll consider it but it will be lower on my list.
