### ISSUE TITLE
How to get that Snapshot goodness

### ISSUE THREAD

**Issue by salamanders** [EdwardRaff/JSAT#46]
the pom.xml has `0.0.7-SNAPSHOT`
and the readme has `I will also host a snapshot directory, to access it - change "maven-repo" to "maven-snapshot-repo" for the "<url>" tag.`

Which is both great - but can anyone tell me how to make use of that?  Which "maven-repo" do I change where?

**Comment by EdwardRaff** [comment]
Ahh, that's out of date. I haven't been doing that for a while. Sorry, I'll remove that tomorrow.

**Comment by EdwardRaff** [comment]
Tomorrow is here! Don't ask me how time works. Put the note on the README so closing this thread.
