### ISSUE TITLE
Kernal Density Estimation

### ISSUE THREAD

**Issue by shanums** [EdwardRaff/JSAT#57]
Hi,
I have a 1D array of some certain values.I want to plot the kernel density estimation of my array. I want to play with the bandwidth and all. I have been using matlab and there I have a function called ksdensity. Now I want to create a kernel density estimation using java. Could you please help  me, How can I find the kernel density estimation of a 1D array.?

**Comment by chhh** [comment]
Look at this unit test: [KernelDensityEstimatorTest.java](https://github.com/EdwardRaff/JSAT/blob/9b914c6015b1e8643af475c287ee350043b07fd6/JSAT/test/jsat/distributions/empirical/KernelDensityEstimatorTest.java)

**Comment by EdwardRaff** [comment]
@chhh Has pointed you to the right class. You can adjust all that from there.
