### ISSUE TITLE
Cannot load arff file

### ISSUE THREAD

**Issue by Microsamp** [EdwardRaff/JSAT#59]
Hey, i tried to load my new arff file, but i'm getting the following stacktrace: 

java.lang.NullPointerException
        at jsat.ARFFLoader.loadArffFile(ARFFLoader.java:182)

my file: 
test4.arff

https://hastebin.com/ewopaxateh.pl

My maven dependencie:

[dependency]
        [groupId>com.edwardraff</groupId]
        [artifactId>JSAT</artifactId]
        [version>0.0.6[/version]
      [/dependency]

My Code:
File in = new File("test4.arff");
SimpleDataSet simpleDataSet = ARFFLoader.loadArffFile(new FileReader(in));

**Comment by Microsamp** [comment]
Ok, i found the following line:
1.551119433032508,0.19167404120454595,1.2476491063357202,"Missing Value"

I think that's the issue. 
I'm trying to delete all this lines and to import the file again.

**Comment by EdwardRaff** [comment]
That is indeed the issue, that makes it an invalid arff file. Missing values are denoted with "?". See [this](http://www.cs.waikato.ac.nz/ml/weka/arff.html) for more info.
