### ISSUE TITLE
DataSet / DataPoint interface

### ISSUE THREAD

**Issue by erosval** [EdwardRaff/JSAT#62]
In order to facilitate the use of the library, is possible to have some interface like other library?
You can look at "Apache Commons Math" where point are interface of Clusterable.

Here some reference:
[Clustering algorithms and distance measures](https://commons.apache.org/proper/commons-math/userguide/ml.html#clustering)
[Clusterable](http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math4/ml/clustering/Clusterable.html)
[DBSCANClusterer](http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math4/ml/clustering/DBSCANClusterer.html)

**Comment by EdwardRaff** [comment]
JSAT already has many such interfaces. For example, here is the one for clustering algorithms 
http://www.edwardraff.com/jsat_docs/JSAT-0.0.8-javadoc/jsat/clustering/Clusterer.html

**Comment by erosval** [comment]
Thanks for the quick reply.
I'll try following these instructions.
The problem for me is that DateSet is not an interface.
What we need is an _"Interface for n-dimensional points that can be clustered together"_.

**Comment by EdwardRaff** [comment]
I still don't understand your request. Why would you want that? A dataset is more generic than needing to be clustered (and is an abstract class) . Clustering is a task that takes a dataset, and given the interface there are many clustering algorithms to use. I'm not seeing how this isn't covered by the current code.

**Comment by erosval** [comment]
The problem is that a DataSet is not an interface.

If I need to "cluster" a set of point in a java array what I have to do?
Using Apache Math the only thing to do is to implement an interface:
`public class Point implements Clusterable {`

Sorry but here is a big difference from `interface `to `abstract class`.

**Comment by EdwardRaff** [comment]
You need to convert your data to an instance of a DataSet , which can then be clustered. Please look at the clustering examples in the wiki

**Comment by erosval** [comment]
Could you suggest an example in which a vector of geographic points is converted to a dataset?
I only have a list of points (x,y) so I cannot use `ARFFLoader `or something else as in the simplest example I found.

I also need to calculate distance between points only if necessary and not pre-calculate every distance.

Apache Commons Math respond to all these requirement but is not complete as your library

**Comment by EdwardRaff** [comment]
You can create a List of [DataPoint](http://www.edwardraff.com/jsat_docs/JSAT-0.0.8-javadoc/jsat/classifiers/DataPoint.html#DataPoint-jsat.linear.Vec-) objects  which can be used to create  [SimpleDataSet object from that list](http://www.edwardraff.com/jsat_docs/JSAT-0.0.8-javadoc/jsat/SimpleDataSet.html#SimpleDataSet-java.util.List- ). You can create a [DenseVector object from a simple array](http://www.edwardraff.com/jsat_docs/JSAT-0.0.8-javadoc/jsat/linear/DenseVector.html). 

>I also need to calculate distance between points only if necessary and not pre-calculate every distance.

All of the JSAT clustering algorithms based on distance metrics will do this by default, unless its not possible to do it that way. 

 I'm on vacation this week, so I really can't help any more than this at this time.
