### ISSUE TITLE
Bug in the ARFFLoader

### ISSUE THREAD

**Issue by KaiJanis** [EdwardRaff/JSAT#63]
While loading an ARFF file, there's a bug with the naming of numeric variables:
Line 199: There is no need to use the helper variable k.
Simple Example: The list "variableNames" contains "A", "B", "C". "A" is a categorical variable.
Inside your loop, you check if the variable is numeric, so in the first iteration no name will be set, i will be 1 and k is 0. In the second iteration you use k to get name. Normally this should be "B", but because k is 0, you will get "A", which is wrong.
So just remove k and use i and everything will be fine.

**Comment by EdwardRaff** [comment]
Do you have a simple test case that can reproduce this? I’m busy at the moment, but will look into this when I get a chance.

**Comment by KaiJanis** [comment]
This is a simple test case for you:
[ARFFTest.txt](https://github.com/EdwardRaff/JSAT/files/1171175/ARFFTest.txt)

Like you can see, the second numeric attribute has the name of the categorical attribute.

**Comment by EdwardRaff** [comment]
You should start from 0 index instead of 1 in your test case. But either way, thanks! Bug is fixed now. Sorry for the delay, I've been busy!
