### ISSUE TITLE
Plotting Library for big data

### ISSUE THREAD

**Issue by aminaaslam** [EdwardRaff/JSAT#64]
Hi Edward,
I am looking for a plotting library that can plot a scatter plot from big dataset(2 Million) rows. Does your visualization library support big data plotting? 
Thanks,

**Comment by EdwardRaff** [comment]
JSAT only provides algorithms, no GUI components. 

If you feel like getting dirty, you can try [JSATFX](https://github.com/EdwardRaff/JSATFX) , which is a operate project but integrates easily with JSAT. It has some convenient plotting tools, but I don't know how well it will handle 2 million datum's. It also doesn't have great documentation, so at your own peril! 

You probably want to be looking at specialized tools / library specifically for plotting large datasets. Some of my friends like [JChart2D](http://jchart2d.sourceforge.net/index.shtml), but again, no idea how well it will handle 2M points.
