### ISSUE TITLE
Very pleased with author update quickly，Other bugs I find：

### ISSUE THREAD

**Issue by junphine** [EdwardRaff/JSAT#68]
jsat.clustering.FLAME
line 340
int len = Math.min(weights[i].length, knns.size()); //modify by me,
// if knns.size is less than weights[i].length there is a  IndexOutOfBoundsException throw.

jsat.clustering.kmeans.NaiveKMeans
line 170
final CountDownLatch latch = new CountDownLatch(blockSize>0? SystemInfo.LogicalCores : extra);
//dataSet size is less than LogicalCores, CountDownLatch  will never down to 0 .

**Comment by EdwardRaff** [comment]
Do you have unit tests that will causes these bugs so I can replicate and add them to the larger unit tests in JSAT?

**Comment by junphine** [comment]
Sorry， there is no unit tests。 just  debug code find it。
case 1 occurred in dataset is very small.
case 2 occurred in  NaiveKMeans as base clusterer  in DivisiveGlobalClusterer

**Comment by EdwardRaff** [comment]
FLAME has been corrected to throw an error. Adjusting k on the fly isn't the correct behavior, and you really shouldn't even be clustering datasets with that few points. 

I was able to reproduce and fix the 2nd bug with NaiveKMeans.
