### ISSUE TITLE
Kernal Density Estimation

### ISSUE THREAD

**Issue by blankFY** [EdwardRaff/JSAT#70]
Hi,
I have a 1D array of some certain values.I want to plot the kernel density estimation of my array. I want to play with the bandwidth and all. I have been using matlab and there I have a function called ksdensity. Now I want to create a kernel density estimation using python.The existing algorithm can not give me results as matlab. Could you please help me, How can I find the kernel density estimation of a 1D array.? Thank you.

**Comment by EdwardRaff** [comment]
The KernelDensityEstimator class is specifically for 1D data, and allows you to query it as a probability distribution. You can use the `setBandwith` method to change the bandwidth.
