### ISSUE TITLE
question on image classifcation

### ISSUE THREAD

**Issue by knasim** [EdwardRaff/JSAT#72]
nice lib - seems to have all the common algos.

question - which sections are more relevant to image classification ?  given a large dataset, and let's say each image is 28X28 pixels - I'd like to compare against a large dataset to determine the image type.  let's take traffic signs for sake of argument.

**Comment by EdwardRaff** [comment]
You should be looking at using GPUs and convolutional neural networks in that case. Because Java doesn't interface well with GPUs, this isn't something I've implemented in JSAT. 

I'd recommend you look at Keras for initial work
