### ISSUE TITLE
Consider moving to a more liberal license

### ISSUE THREAD

**Issue by xamde** [EdwardRaff/JSAT#75]
Hi, I would like to take parts of JSAT, cross-compile them using GWT (your pure-Java style will greatly help) and use them in a (maybe one day commercial) project. Why not just use MIT, BSD or Apache 2.0 license? Thanks for considering!

**Comment by EdwardRaff** [comment]
Hi xamde, glad JSAT looks like it might be useful! 

I have no intentions on changing the license of JSAT, and have discussed this in short in my [FAQ](https://github.com/EdwardRaff/JSAT/wiki/FAQ#will-you-please-change-the-license-from-gpl-to-bsd--mit--apache--other). If companies want to use my code for commercial work, they are free to either abide by the GPL or reach out to me for an alternative license in exchange for some kind of compensation.
