### ISSUE TITLE
Question: Mean-Shift Starting point

### ISSUE THREAD

**Issue by akm0012** [EdwardRaff/JSAT#77]
Hello,

Very impressed with this library! 

Here is my problem: I have a bunch photos that have: Latitude, Longitude, and time data points. I need to cluster them together as to form groups of photos that were taken in the same area, around the same time.  I've done some research on clustering, and I think using the Mean-Shift algorithm will suite this nicely. Mainly because I do not know in advance the number of clusters there will be.

I wanted to use your library to help me with that, and I'm having trouble getting started. I have looked though your wiki, but still a little lost on how to begin. Any advice or code snippets would be awesome!

Thanks!

**Comment by EdwardRaff** [comment]
Is your data stored in a file, or created while running? I would start with [this example](https://github.com/EdwardRaff/JSAT/wiki/How-to-load-a-data-set) on getting your dataset loaded into a JSAT object. 

You will then want to look at this [clustering example](https://github.com/EdwardRaff/JSAT/wiki/K-Means-and-Finding-%22K%22) fromt he wiki, and in particular the code below has most of what you need:

```java
            //print out the number of clusters chosen and the evaluation for each automatic version of k-means
            int[] clusteringResults = new int[data.getSampleSize()];//hold the clustering results, this version is manditory to use NMI
            for( Clusterer clusterer : methodsToEval.values())
            {
                //when we call this constructor, the algorithm is expected to figure out the number of clusters on its own
               clusterer.cluster(data, clusteringResults);
                //the number of clusters found can be determined from the maximimum cluster ID returned, +1 since 0 is a cluster ID. 
                int kFound = IntStream.of(clusteringResults).max().getAsInt()+1;;
                System.out.printf("%4d , %.3f | ",kFound, evaluator.evaluate(clusteringResults, data));
            }
```

I would start with that, and if you have more specific questions, feel free to follow up.

**Comment by akm0012** [comment]
Data is created while running on a background thread.
