### ISSUE TITLE
JSAT and Graylog plugin

### ISSUE THREAD

**Issue by dio99** [EdwardRaff/JSAT#79]
i got an question about this jsat if it would be possible to get some hints about how i could create this for a logtool Graylog and using this as a plugin in graylog
https://github.com/Graylog2/graylog-plugin-sample/tree/2.2
http://docs.graylog.org/en/2.4/pages/plugins.html?highlight=plugin

**Comment by EdwardRaff** [comment]
Thats something you should ask the Graylog people/project. I know nothing about it or how you would apply machine learning to whatever that project does.
