### ISSUE TITLE
Update Maven

### ISSUE THREAD

**Issue by Tinq06** [EdwardRaff/JSAT#81]
Hi Edward Raff,

I'm wondering if you can update the maven repository, i'm using the 0.0.9 and i see that it's not updated with the currently GitHub since 2 years.

Thanks you ! :)

**Comment by EdwardRaff** [comment]
On my todo list! I had a lot of refactoring that I wanted to do for 0.1.0
and the move to Java 8... but health & life got in the way. Looks like I
need to accept that it wont be as grand a update as I hoped!

**Comment by Tinq06** [comment]
Thanks you !
