### ISSUE TITLE
Decision Tree Algorithm

### ISSUE THREAD

**Issue by jayrar** [EdwardRaff/JSAT#82]
Hello,
I would to know which algorithm you have implemented in the class DecisionTree.
thank you in advance,
Jayrar.

**Comment by EdwardRaff** [comment]
The implementation in JSAT doesn't follow a single "specific" algorithm, and has options to change how different parts are handled. 

All of the components to make the JSAT implementation equivalent to a C4.5 tree are there, and thus the `DecisionTree.getC45Tree()` method returns one with that parameterization.
