### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [EdwardRaff/JSAT#98]
Some preliminary notes prior to a PR.

```
$ sed -n 267,270p JSAT/JSAT/src/jsat/classifiers/svm/SVMnoBias.java
                    //We call k instead of kEval b/c we are accing most 
                    //of the n^2 values, so nothing will get to stay in 
                    //cache. Unless we are using FULL cacheing, in which
                    //case we will get re-use. 
$ 
```
@EdwardRaff

Is there a fix for `accing` in the above?

`sed -i 's/cacheing/caching/g' JSAT/JSAT/src/jsat/classifiers/svm/SVMnoBias.java`

**Comment by EdwardRaff** [comment]
What do you mean fix? Sorry I'm not following.

**Comment by spaette** [comment]
Does the string `accing` constitute a typographical error?

**Comment by spaette** [comment]
My mistake.
